<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.5.0/dist/semantic.min.css">
    <link rel="stylesheet" href="src/css/style.css">


    <title>TDF</title>
</head>

<body>
<div class="ui secondary menu">
    <a class="item" href="index.php">
        <i class="ui icon home"></i>
    </a>
    <a class="item" href="coureurs.php">
        Cyclistes
    </a>
    <a class="item" href="edition.php">
        Editions TDF
    </a>
    <div class="ui dropdown item">
        <i class="dropdown icon"> </i>
        Insertions
        <div class="menu">
            <a class="item" href="insertion_coureur.php">Insertion d'un coureur</a>
            <a class="item" href="insertion_equipe.php">Insertion d'une équipe</a>
            <a class="item" href="insertion_parti_coureur.php">Insertion d'une participation pour un coureur</a>
            <a class="item" href="insertion_parti_equipe.php">Insertion d'une participation pour une équipe</a>
        </div>
    </div>
</div>


