<div class="ui segment parent">
    <div class="gridHead">
        <button class="ui button" onclick="window.location.href='coureurs.php'"><i class="arrow left icon"></i>Retour</button>
        <?php if ($anneeCorrecte): ?>
            <button class="ui button" onclick="window.location.href='insertion_parti_coureur.php'"><i class="arrow left icon"></i>Changer d'édition</button>
        <?php endif; ?>
        <div class="ui raised padded segment">
            <form class="ui form <?php if ($erreur) echo ' error';?>" action="" method="get"> <!-- class error will show error message-->
                <h4 class="ui dividing header">Insertion d'une participation pour un coureur</h4>
                <!--Choix de l'édition-->
                    <div class="field" id="annee_field">
                        <label for="annee">Choix de l'édition</label>
                        <input type="number" id="annee" name="ANNEE" placeholder="Entrez une année..." value="<?php verifierTextGET("ANNEE");?>" <?php if ($anneeCorrecte) echo "disabled";?>>
                    </div>

                <?php if ($anneeCorrecte): ?>
                <!--Si l'année est correcte, on peut alors demander le coureur et son équipe à l'utilisateur-->
            </form>
                <form class="ui form <?php if ($erreur) echo ' error';?>" action="" method="post"> <!-- class error will show error message-->

                <!--Sélection du coureur-->
                    <div class="field" id="coureur_field">
                        <label for="menu">Coureur*</label>
                        <a href="insertion_coureur.php">Ajouter un coureur</a>
                        <div class="ui fluid search selection dropdown">
                            <input type="hidden" name="N_COUREUR" <?php if(isset($_POST['N_COUREUR'])) echo "value=\"".$_POST['N_COUREUR']."\""?>>
                            <i class="dropdown icon"></i>
                            <div class="default text">Sélectionnez un coureur ...</div>
                            <div class="menu" id="menuCoureur">
                            <?php
                            $res = $conn->query("select c.NOM || ' ' || c.PRENOM as COUREUR, c.N_COUREUR, n.NOM as NATION,  lower(substr(CODE_ISO, 0, 2)) as CODE_ISO from TDF_COUREUR c
                                                            join TDF_APP_NATION TAN on c.N_COUREUR = TAN.N_COUREUR
                                                            join TDF_NATION n on TAN.CODE_CIO = n.CODE_CIO
                                                            where ANNEE_DEBUT =
                                                            (
                                                                    select max(ANNEE_DEBUT) from TDF_APP_NATION TAN2
                                                                    where TAN2.N_COUREUR = c.N_COUREUR
                                                                    and TAN2.ANNEE_DEBUT <= $annee
                                                                    group by N_COUREUR
                                                                        )
                                                            order by c.NOM")->fetchAll(PDO::FETCH_ASSOC);
                            foreach ($res as $coureur) :?>
                                <div class="item" data-value="<?= $coureur['N_COUREUR'];?>"><i class="<?= $coureur['CODE_ISO'] ?> flag"></i><?=$coureur['COUREUR'];?></div>
                            <?php endforeach; ?>
                            </div>
                        </div>
                    </div>

                    <!--Sélection d'une équipe -->
                    <div class="field" id="equipe_field">
                        <label for="menuEquipe">Equipe*</label>
                        <a href="insertion_parti_equipe.php" > Ajouter une equipe</a>

                        <div class="ui fluid search selection dropdown">
                            <input type="hidden" name="EQUIPE" <?php if(isset($_POST['EQUIPE'])) echo "value=\"".$_POST['EQUIPE']."\""?>>

                            <i class="dropdown icon"></i>
                            <div class="default text">Sélectionnez une equipe ...</div>
                            <div class="menu" id="menuEquipe">
                                <?php
                                $req = $conn->prepare("select N_EQUIPE, N_SPONSOR, TDF_SPONSOR.NOM as NOM, lower(substr(CODE_ISO, 0, 2)) as CODE_ISO from TDF_PARTI_EQUIPE e
                                                                    join TDF_SPONSOR  using(N_SPONSOR, N_EQUIPE)
                                                                    join TDF_NATION using (CODE_CIO)   
                                                                    where ANNEE = :annee
                                                                    order by TDF_SPONSOR.NOM");
                                $req->bindParam(':annee', $_GET['ANNEE']);
                                $req->execute();
                                $res = $req->fetchAll(PDO::FETCH_ASSOC);
                                foreach ($res as $equipe) :?>
                                    <div class="item" data-value="<?=$equipe['N_EQUIPE'] . '~' . $equipe['N_SPONSOR'];?>"><i class="<?= $equipe['CODE_ISO'] ?> flag"></i><?=$equipe['NOM'];?></div>
                                <?php endforeach;?>
                            </div>
                        </div>
                    </div>

                    <?php if ($premier): ?>
                        <!--Premier coureur de l'équipe alors on demande le N_dossard-->
                        <div class="field" id="dossard_field">
                            <label for="dossard">N° de dossard*</label>
                            <input type="number" id="dossard" name="N_DOSSARD" placeholder="Entrez le numéro de dossard" value="<?php verifierText("N_DOSSARD");?>">
                        </div>
                    <?php endif; ?>

                    <button id="subButton" class="ui button" type="submit" name="subButton" value="Envoyer">Insérer la participation</button>

                    <?php else: ?>
                        <!--sinon l'année n'est pas renseignée
                        On affiche ce bouton-->
                        <button type="submit" value="annee" class="ui button">Valider</button>
                    <?php endif; ?>


                </form>
        </div>
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.5.0/dist/semantic.min.js"></script>
<script src="src/js/script.js"></script>



<script>
    //semantic UI
    $('.ui.dropdown').dropdown();
    $.fn.dropdown.settings.message.noResults = 'Aucun résultat trouvé pour cette édition';


    function tdfInput(){
        document.getElementById("coureur_field").hidden = document.getElementById("tdf_field").value === "";
        if (document.getElementById("tdf_field").value !== ""){
            getCoureurs(document.getElementById("tdf_field").value);
            getEquipes(document.getElementById("tdf_field").value);
        }

        else{
            document.getElementById("coureur_field").hidden = true;
        }
    }

    <?php
        //affichage des erreurs sur le formulaire
        afficheErreurField("coureur_field", $erreurCoureur);
        afficheErreurField("annee_field", $erreurAnnee);
        afficheErreurField("equipe_field", $erreurEquipe);
        afficheErreurField("dossard_field", $erreurDossard);


    ?>


</script>